//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AFSCustomerOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSCustomerOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSCustomer"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdditionalInfo" type="{http://Horizon.ExternalServices.AFS}ArrayOfAFSCustomerAdditionalInfoEntry" minOccurs="0"/&gt;
 *         &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_Organization_PersonalNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_PaymentExperience" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_PostalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CI_PostalPlace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CurrencyDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CustomerBalanceBought" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CustomerBalanceOverDue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="DirectDebetStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InterestStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="InterestStopDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="InvalidOrganization_PersonalNo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="LoanStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Rating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RatingDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ReminderStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReminderStopDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSCustomerOutput", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "additionalInfo",
    "bankAccount",
    "ciAddress",
    "ciFirstName",
    "ciLastName",
    "ciOrganizationPersonalNo",
    "ciPaymentExperience",
    "ciPostalCode",
    "ciPostalPlace",
    "country",
    "creditLimit",
    "currencyDescription",
    "customerBalance",
    "customerBalanceBought",
    "customerBalanceOverDue",
    "directDebetStatus",
    "interestStop",
    "interestStopDate",
    "invalidOrganizationPersonalNo",
    "loanStop",
    "purchaseStop",
    "rating",
    "ratingDate",
    "reminderStop",
    "reminderStopDate"
})
public class AFSCustomerOutput
    extends AFSCustomer
{

    @XmlElementRef(name = "AdditionalInfo", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAFSCustomerAdditionalInfoEntry> additionalInfo;
    @XmlElementRef(name = "BankAccount", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bankAccount;
    @XmlElementRef(name = "CI_Address", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciAddress;
    @XmlElementRef(name = "CI_FirstName", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciFirstName;
    @XmlElementRef(name = "CI_LastName", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciLastName;
    @XmlElementRef(name = "CI_Organization_PersonalNo", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciOrganizationPersonalNo;
    @XmlElementRef(name = "CI_PaymentExperience", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciPaymentExperience;
    @XmlElementRef(name = "CI_PostalCode", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciPostalCode;
    @XmlElementRef(name = "CI_PostalPlace", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ciPostalPlace;
    @XmlElementRef(name = "Country", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> country;
    @XmlElement(name = "CreditLimit")
    protected BigDecimal creditLimit;
    @XmlElementRef(name = "CurrencyDescription", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currencyDescription;
    @XmlElement(name = "CustomerBalance")
    protected BigDecimal customerBalance;
    @XmlElement(name = "CustomerBalanceBought")
    protected BigDecimal customerBalanceBought;
    @XmlElement(name = "CustomerBalanceOverDue")
    protected BigDecimal customerBalanceOverDue;
    @XmlElementRef(name = "DirectDebetStatus", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> directDebetStatus;
    @XmlElement(name = "InterestStop")
    protected Boolean interestStop;
    @XmlElement(name = "InterestStopDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar interestStopDate;
    @XmlElement(name = "InvalidOrganization_PersonalNo")
    protected Boolean invalidOrganizationPersonalNo;
    @XmlElement(name = "LoanStop")
    protected Boolean loanStop;
    @XmlElement(name = "PurchaseStop")
    protected Boolean purchaseStop;
    @XmlElementRef(name = "Rating", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> rating;
    @XmlElementRef(name = "RatingDate", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> ratingDate;
    @XmlElement(name = "ReminderStop")
    protected Boolean reminderStop;
    @XmlElement(name = "ReminderStopDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reminderStopDate;

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSCustomerAdditionalInfoEntry }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAFSCustomerAdditionalInfoEntry> getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSCustomerAdditionalInfoEntry }{@code >}
     *     
     */
    public void setAdditionalInfo(JAXBElement<ArrayOfAFSCustomerAdditionalInfoEntry> value) {
        this.additionalInfo = value;
    }

    /**
     * Gets the value of the bankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBankAccount() {
        return bankAccount;
    }

    /**
     * Sets the value of the bankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBankAccount(JAXBElement<String> value) {
        this.bankAccount = value;
    }

    /**
     * Gets the value of the ciAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIAddress() {
        return ciAddress;
    }

    /**
     * Sets the value of the ciAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIAddress(JAXBElement<String> value) {
        this.ciAddress = value;
    }

    /**
     * Gets the value of the ciFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIFirstName() {
        return ciFirstName;
    }

    /**
     * Sets the value of the ciFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIFirstName(JAXBElement<String> value) {
        this.ciFirstName = value;
    }

    /**
     * Gets the value of the ciLastName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCILastName() {
        return ciLastName;
    }

    /**
     * Sets the value of the ciLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCILastName(JAXBElement<String> value) {
        this.ciLastName = value;
    }

    /**
     * Gets the value of the ciOrganizationPersonalNo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIOrganizationPersonalNo() {
        return ciOrganizationPersonalNo;
    }

    /**
     * Sets the value of the ciOrganizationPersonalNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIOrganizationPersonalNo(JAXBElement<String> value) {
        this.ciOrganizationPersonalNo = value;
    }

    /**
     * Gets the value of the ciPaymentExperience property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIPaymentExperience() {
        return ciPaymentExperience;
    }

    /**
     * Sets the value of the ciPaymentExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIPaymentExperience(JAXBElement<String> value) {
        this.ciPaymentExperience = value;
    }

    /**
     * Gets the value of the ciPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIPostalCode() {
        return ciPostalCode;
    }

    /**
     * Sets the value of the ciPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIPostalCode(JAXBElement<String> value) {
        this.ciPostalCode = value;
    }

    /**
     * Gets the value of the ciPostalPlace property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCIPostalPlace() {
        return ciPostalPlace;
    }

    /**
     * Sets the value of the ciPostalPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCIPostalPlace(JAXBElement<String> value) {
        this.ciPostalPlace = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCountry(JAXBElement<String> value) {
        this.country = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditLimit(BigDecimal value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the currencyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrencyDescription() {
        return currencyDescription;
    }

    /**
     * Sets the value of the currencyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrencyDescription(JAXBElement<String> value) {
        this.currencyDescription = value;
    }

    /**
     * Gets the value of the customerBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomerBalance() {
        return customerBalance;
    }

    /**
     * Sets the value of the customerBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomerBalance(BigDecimal value) {
        this.customerBalance = value;
    }

    /**
     * Gets the value of the customerBalanceBought property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomerBalanceBought() {
        return customerBalanceBought;
    }

    /**
     * Sets the value of the customerBalanceBought property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomerBalanceBought(BigDecimal value) {
        this.customerBalanceBought = value;
    }

    /**
     * Gets the value of the customerBalanceOverDue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCustomerBalanceOverDue() {
        return customerBalanceOverDue;
    }

    /**
     * Sets the value of the customerBalanceOverDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCustomerBalanceOverDue(BigDecimal value) {
        this.customerBalanceOverDue = value;
    }

    /**
     * Gets the value of the directDebetStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirectDebetStatus() {
        return directDebetStatus;
    }

    /**
     * Sets the value of the directDebetStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirectDebetStatus(JAXBElement<String> value) {
        this.directDebetStatus = value;
    }

    /**
     * Gets the value of the interestStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInterestStop() {
        return interestStop;
    }

    /**
     * Sets the value of the interestStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInterestStop(Boolean value) {
        this.interestStop = value;
    }

    /**
     * Gets the value of the interestStopDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInterestStopDate() {
        return interestStopDate;
    }

    /**
     * Sets the value of the interestStopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInterestStopDate(XMLGregorianCalendar value) {
        this.interestStopDate = value;
    }

    /**
     * Gets the value of the invalidOrganizationPersonalNo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInvalidOrganizationPersonalNo() {
        return invalidOrganizationPersonalNo;
    }

    /**
     * Sets the value of the invalidOrganizationPersonalNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInvalidOrganizationPersonalNo(Boolean value) {
        this.invalidOrganizationPersonalNo = value;
    }

    /**
     * Gets the value of the loanStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoanStop() {
        return loanStop;
    }

    /**
     * Sets the value of the loanStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoanStop(Boolean value) {
        this.loanStop = value;
    }

    /**
     * Gets the value of the purchaseStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPurchaseStop() {
        return purchaseStop;
    }

    /**
     * Sets the value of the purchaseStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPurchaseStop(Boolean value) {
        this.purchaseStop = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRating(JAXBElement<String> value) {
        this.rating = value;
    }

    /**
     * Gets the value of the ratingDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getRatingDate() {
        return ratingDate;
    }

    /**
     * Sets the value of the ratingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setRatingDate(JAXBElement<XMLGregorianCalendar> value) {
        this.ratingDate = value;
    }

    /**
     * Gets the value of the reminderStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReminderStop() {
        return reminderStop;
    }

    /**
     * Sets the value of the reminderStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReminderStop(Boolean value) {
        this.reminderStop = value;
    }

    /**
     * Gets the value of the reminderStopDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReminderStopDate() {
        return reminderStopDate;
    }

    /**
     * Sets the value of the reminderStopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReminderStopDate(XMLGregorianCalendar value) {
        this.reminderStopDate = value;
    }

}
