//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSInvoiceTextOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSInvoiceTextOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSObjectBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountOfferMinimumToPay" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="AccountOfferText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BankAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceTextInfo" type="{http://Horizon.ExternalServices.AFS}ArrayOfAFSInvoiceTextInfoEntry" minOccurs="0"/&gt;
 *         &lt;element name="LogonText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OCRNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSInvoiceTextOutput", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "accountOfferMinimumToPay",
    "accountOfferText",
    "bankAccountNumber",
    "invoiceTextInfo",
    "logonText",
    "ocrNumber"
})
public class AFSInvoiceTextOutput
    extends AFSObjectBase
{

    @XmlElementRef(name = "AccountOfferMinimumToPay", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> accountOfferMinimumToPay;
    @XmlElementRef(name = "AccountOfferText", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> accountOfferText;
    @XmlElementRef(name = "BankAccountNumber", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bankAccountNumber;
    @XmlElementRef(name = "InvoiceTextInfo", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAFSInvoiceTextInfoEntry> invoiceTextInfo;
    @XmlElementRef(name = "LogonText", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> logonText;
    @XmlElementRef(name = "OCRNumber", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> ocrNumber;

    /**
     * Gets the value of the accountOfferMinimumToPay property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getAccountOfferMinimumToPay() {
        return accountOfferMinimumToPay;
    }

    /**
     * Sets the value of the accountOfferMinimumToPay property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setAccountOfferMinimumToPay(JAXBElement<BigDecimal> value) {
        this.accountOfferMinimumToPay = value;
    }

    /**
     * Gets the value of the accountOfferText property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAccountOfferText() {
        return accountOfferText;
    }

    /**
     * Sets the value of the accountOfferText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAccountOfferText(JAXBElement<String> value) {
        this.accountOfferText = value;
    }

    /**
     * Gets the value of the bankAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBankAccountNumber() {
        return bankAccountNumber;
    }

    /**
     * Sets the value of the bankAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBankAccountNumber(JAXBElement<String> value) {
        this.bankAccountNumber = value;
    }

    /**
     * Gets the value of the invoiceTextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSInvoiceTextInfoEntry }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAFSInvoiceTextInfoEntry> getInvoiceTextInfo() {
        return invoiceTextInfo;
    }

    /**
     * Sets the value of the invoiceTextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSInvoiceTextInfoEntry }{@code >}
     *     
     */
    public void setInvoiceTextInfo(JAXBElement<ArrayOfAFSInvoiceTextInfoEntry> value) {
        this.invoiceTextInfo = value;
    }

    /**
     * Gets the value of the logonText property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLogonText() {
        return logonText;
    }

    /**
     * Sets the value of the logonText property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLogonText(JAXBElement<String> value) {
        this.logonText = value;
    }

    /**
     * Gets the value of the ocrNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOCRNumber() {
        return ocrNumber;
    }

    /**
     * Sets the value of the ocrNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOCRNumber(JAXBElement<String> value) {
        this.ocrNumber = value;
    }

}
