//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSOrderResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSOrderResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSResponseBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Customer" type="{http://Horizon.ExternalServices.AFS}AFSCustomerOutput" minOccurs="0"/&gt;
 *         &lt;element name="CustomerCheckStatus" type="{http://Horizon.ExternalServices.AFS}AFSCustomerCheckStatus" minOccurs="0"/&gt;
 *         &lt;element name="Order" type="{http://Horizon.ExternalServices.AFS}AFSOrderOutput" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseStatus" type="{http://Horizon.ExternalServices.AFS}AFSPurchaseStatus" minOccurs="0"/&gt;
 *         &lt;element name="TemporaryExternalProblem" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSOrderResponse", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "customer",
    "customerCheckStatus",
    "order",
    "purchaseStatus",
    "temporaryExternalProblem"
})
@XmlSeeAlso({
    AFSOrderShipmentResponse.class,
    AFSCreditOrderResponse.class
})
public class AFSOrderResponse
    extends AFSResponseBase
{

    @XmlElementRef(name = "Customer", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSCustomerOutput> customer;
    @XmlElementRef(name = "CustomerCheckStatus", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSCustomerCheckStatus> customerCheckStatus;
    @XmlElementRef(name = "Order", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSOrderOutput> order;
    @XmlElementRef(name = "PurchaseStatus", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSPurchaseStatus> purchaseStatus;
    @XmlElement(name = "TemporaryExternalProblem")
    protected Boolean temporaryExternalProblem;

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSCustomerOutput }{@code >}
     *     
     */
    public JAXBElement<AFSCustomerOutput> getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSCustomerOutput }{@code >}
     *     
     */
    public void setCustomer(JAXBElement<AFSCustomerOutput> value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerCheckStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSCustomerCheckStatus }{@code >}
     *     
     */
    public JAXBElement<AFSCustomerCheckStatus> getCustomerCheckStatus() {
        return customerCheckStatus;
    }

    /**
     * Sets the value of the customerCheckStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSCustomerCheckStatus }{@code >}
     *     
     */
    public void setCustomerCheckStatus(JAXBElement<AFSCustomerCheckStatus> value) {
        this.customerCheckStatus = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSOrderOutput }{@code >}
     *     
     */
    public JAXBElement<AFSOrderOutput> getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSOrderOutput }{@code >}
     *     
     */
    public void setOrder(JAXBElement<AFSOrderOutput> value) {
        this.order = value;
    }

    /**
     * Gets the value of the purchaseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSPurchaseStatus }{@code >}
     *     
     */
    public JAXBElement<AFSPurchaseStatus> getPurchaseStatus() {
        return purchaseStatus;
    }

    /**
     * Sets the value of the purchaseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSPurchaseStatus }{@code >}
     *     
     */
    public void setPurchaseStatus(JAXBElement<AFSPurchaseStatus> value) {
        this.purchaseStatus = value;
    }

    /**
     * Gets the value of the temporaryExternalProblem property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTemporaryExternalProblem() {
        return temporaryExternalProblem;
    }

    /**
     * Sets the value of the temporaryExternalProblem property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTemporaryExternalProblem(Boolean value) {
        this.temporaryExternalProblem = value;
    }

}
