//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSPrintOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSPrintOptions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSOptionsBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvoiceDistributionBy" type="{http://schemas.datacontract.org/2004/07/Horizon.AFS.General}AFSInvoiceDistributionBy" minOccurs="0"/&gt;
 *         &lt;element name="InvoiceDistributionType" type="{http://schemas.datacontract.org/2004/07/Horizon.AFS.General}AFSInvoiceDistributionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSPrintOptions", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "invoiceDistributionBy",
    "invoiceDistributionType"
})
public class AFSPrintOptions
    extends AFSOptionsBase
{

    @XmlElement(name = "InvoiceDistributionBy")
    @XmlSchemaType(name = "string")
    protected AFSInvoiceDistributionBy invoiceDistributionBy;
    @XmlElement(name = "InvoiceDistributionType")
    @XmlSchemaType(name = "string")
    protected AFSInvoiceDistributionType invoiceDistributionType;

    /**
     * Gets the value of the invoiceDistributionBy property.
     * 
     * @return
     *     possible object is
     *     {@link AFSInvoiceDistributionBy }
     *     
     */
    public AFSInvoiceDistributionBy getInvoiceDistributionBy() {
        return invoiceDistributionBy;
    }

    /**
     * Sets the value of the invoiceDistributionBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AFSInvoiceDistributionBy }
     *     
     */
    public void setInvoiceDistributionBy(AFSInvoiceDistributionBy value) {
        this.invoiceDistributionBy = value;
    }

    /**
     * Gets the value of the invoiceDistributionType property.
     * 
     * @return
     *     possible object is
     *     {@link AFSInvoiceDistributionType }
     *     
     */
    public AFSInvoiceDistributionType getInvoiceDistributionType() {
        return invoiceDistributionType;
    }

    /**
     * Sets the value of the invoiceDistributionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AFSInvoiceDistributionType }
     *     
     */
    public void setInvoiceDistributionType(AFSInvoiceDistributionType value) {
        this.invoiceDistributionType = value;
    }

}
