//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSPurchaseDeclineReason complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSPurchaseDeclineReason"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSObjectBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeclineDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeclineReason" type="{http://schemas.datacontract.org/2004/07/Horizon.AFS.General}AFSPurchaseDeclineReasonCodes" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSPurchaseDeclineReason", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "declineDescription",
    "declineReason"
})
public class AFSPurchaseDeclineReason
    extends AFSObjectBase
{

    @XmlElementRef(name = "DeclineDescription", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> declineDescription;
    @XmlElement(name = "DeclineReason")
    @XmlSchemaType(name = "string")
    protected AFSPurchaseDeclineReasonCodes declineReason;

    /**
     * Gets the value of the declineDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDeclineDescription() {
        return declineDescription;
    }

    /**
     * Sets the value of the declineDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDeclineDescription(JAXBElement<String> value) {
        this.declineDescription = value;
    }

    /**
     * Gets the value of the declineReason property.
     * 
     * @return
     *     possible object is
     *     {@link AFSPurchaseDeclineReasonCodes }
     *     
     */
    public AFSPurchaseDeclineReasonCodes getDeclineReason() {
        return declineReason;
    }

    /**
     * Sets the value of the declineReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link AFSPurchaseDeclineReasonCodes }
     *     
     */
    public void setDeclineReason(AFSPurchaseDeclineReasonCodes value) {
        this.declineReason = value;
    }

}
