//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSRatingUpdateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AFSRatingUpdateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RefreshRatingIfOld"/&gt;
 *     &lt;enumeration value="RefreshRating"/&gt;
 *     &lt;enumeration value="UseLocalRating"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AFSRatingUpdateType", namespace = "http://schemas.datacontract.org/2004/07/Horizon.AFS.General")
@XmlEnum
public enum AFSRatingUpdateType {

    @XmlEnumValue("RefreshRatingIfOld")
    REFRESH_RATING_IF_OLD("RefreshRatingIfOld"),
    @XmlEnumValue("RefreshRating")
    REFRESH_RATING("RefreshRating"),
    @XmlEnumValue("UseLocalRating")
    USE_LOCAL_RATING("UseLocalRating");
    private final String value;

    AFSRatingUpdateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AFSRatingUpdateType fromValue(String v) {
        for (AFSRatingUpdateType c: AFSRatingUpdateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
