//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSResponseBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSResponseBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices}ResponseBase"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSResponseBase", namespace = "http://Horizon.ExternalServices.AFS")
@XmlSeeAlso({
    AFSCustomerResponse.class,
    AFSCustomerPurchaseResponse.class,
    AFSCustomerLimitResponse.class,
    AFSLedgerResponse.class,
    AFSInvoiceResponse.class,
    AFSInvoiceGetResponse.class,
    AFSOrderSearchResponse.class,
    AFSReportDocumentResponse.class,
    AFSReportLinkResponse.class,
    AFSOrderResponse.class,
    AFSAccountTermsAndConditionsResponse.class,
    AFSAccountTermsAndConditionsSecciResponse.class,
    AFSAcceptAccountTermsAndConditionsResponse.class,
    AFSAccountCheckCustomerHasAccountResponse.class,
    AFSReservationResponse.class,
    AFSReservationWithPaymentTypeResponse.class,
    AFSCancelReservationResponse.class,
    AFSCheckCustomerAndReservationResponse.class,
    AFSInvoiceTextResponse.class,
    AFSUpdateInvoiceDueDateResponse.class,
    AFSUpdateInvoiceStopFlagsResponse.class,
    AFSUpdateMerchantInfoResponse.class,
    AFSGetDirectDebitContractResponse.class,
    AFSAcceptDirectDebitContractResponse.class,
    AFSGetClientLimitResponse.class,
    AFSResponse.class
})
public class AFSResponseBase
    extends ResponseBase
{


}
