//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TraceMessage"/&gt;
 *     &lt;enumeration value="InfoMessage"/&gt;
 *     &lt;enumeration value="BusinessLogic"/&gt;
 *     &lt;enumeration value="ValidationError"/&gt;
 *     &lt;enumeration value="SystemError"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageTypes", namespace = "http://schemas.datacontract.org/2004/07/Horizon.ExternalServices.General")
@XmlEnum
public enum MessageTypes {

    @XmlEnumValue("TraceMessage")
    TRACE_MESSAGE("TraceMessage"),
    @XmlEnumValue("InfoMessage")
    INFO_MESSAGE("InfoMessage"),
    @XmlEnumValue("BusinessLogic")
    BUSINESS_LOGIC("BusinessLogic"),
    @XmlEnumValue("ValidationError")
    VALIDATION_ERROR("ValidationError"),
    @XmlEnumValue("SystemError")
    SYSTEM_ERROR("SystemError");
    private final String value;

    MessageTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageTypes fromValue(String v) {
        for (MessageTypes c: MessageTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
