//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSAdditionalReservationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSAdditionalReservationInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSObjectBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DirectDebetBankAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DirectDebetBankID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InstallmentInfo" type="{http://Horizon.ExternalServices.AFS}AFSInstallmentInfo" minOccurs="0"/&gt;
 *         &lt;element name="OrderLines" type="{http://Horizon.ExternalServices.AFS}ArrayOfAFSOrderLine" minOccurs="0"/&gt;
 *         &lt;element name="PaymentMethod" type="{http://schemas.datacontract.org/2004/07/Horizon.ExternalServices.AFS.General.Reservation}AFSPaymentMethod" minOccurs="0"/&gt;
 *         &lt;element name="TermsAndConditionAcceptID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSAdditionalReservationInfo", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "directDebetBankAccount",
    "directDebetBankID",
    "installmentInfo",
    "orderLines",
    "paymentMethod",
    "termsAndConditionAcceptID"
})
public class AFSAdditionalReservationInfo
    extends AFSObjectBase
{

    @XmlElementRef(name = "DirectDebetBankAccount", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> directDebetBankAccount;
    @XmlElementRef(name = "DirectDebetBankID", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> directDebetBankID;
    @XmlElementRef(name = "InstallmentInfo", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSInstallmentInfo> installmentInfo;
    @XmlElementRef(name = "OrderLines", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfAFSOrderLine> orderLines;
    @XmlElement(name = "PaymentMethod")
    @XmlSchemaType(name = "string")
    protected AFSPaymentMethod paymentMethod;
    @XmlElementRef(name = "TermsAndConditionAcceptID", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> termsAndConditionAcceptID;

    /**
     * Gets the value of the directDebetBankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirectDebetBankAccount() {
        return directDebetBankAccount;
    }

    /**
     * Sets the value of the directDebetBankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirectDebetBankAccount(JAXBElement<String> value) {
        this.directDebetBankAccount = value;
    }

    /**
     * Gets the value of the directDebetBankID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDirectDebetBankID() {
        return directDebetBankID;
    }

    /**
     * Sets the value of the directDebetBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDirectDebetBankID(JAXBElement<String> value) {
        this.directDebetBankID = value;
    }

    /**
     * Gets the value of the installmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSInstallmentInfo }{@code >}
     *     
     */
    public JAXBElement<AFSInstallmentInfo> getInstallmentInfo() {
        return installmentInfo;
    }

    /**
     * Sets the value of the installmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSInstallmentInfo }{@code >}
     *     
     */
    public void setInstallmentInfo(JAXBElement<AFSInstallmentInfo> value) {
        this.installmentInfo = value;
    }

    /**
     * Gets the value of the orderLines property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSOrderLine }{@code >}
     *     
     */
    public JAXBElement<ArrayOfAFSOrderLine> getOrderLines() {
        return orderLines;
    }

    /**
     * Sets the value of the orderLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfAFSOrderLine }{@code >}
     *     
     */
    public void setOrderLines(JAXBElement<ArrayOfAFSOrderLine> value) {
        this.orderLines = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link AFSPaymentMethod }
     *     
     */
    public AFSPaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link AFSPaymentMethod }
     *     
     */
    public void setPaymentMethod(AFSPaymentMethod value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the termsAndConditionAcceptID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTermsAndConditionAcceptID() {
        return termsAndConditionAcceptID;
    }

    /**
     * Sets the value of the termsAndConditionAcceptID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTermsAndConditionAcceptID(JAXBElement<String> value) {
        this.termsAndConditionAcceptID = value;
    }

}
