//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AFSInvoiceOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSInvoiceOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSInvoice"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountingMonth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="AccountingYear" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Balance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="BuyCancelledDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="BuyDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="BuyStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscountBalance" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscountDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CashDiscountUsed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Ins" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="InterestStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="InterestStopDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IsBought" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsInterestNote" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="LastEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NextEvent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ProductionStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReminderStop" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReminderStopDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="SentToDebtCollection" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSInvoiceOutput", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "accountingMonth",
    "accountingYear",
    "balance",
    "buyCancelledDate",
    "buyDate",
    "buyStop",
    "cashDiscountBalance",
    "cashDiscountDescription",
    "cashDiscountUsed",
    "ins",
    "interestStop",
    "interestStopDate",
    "isBought",
    "isInterestNote",
    "lastEvent",
    "nextEvent",
    "productionStop",
    "reminderStop",
    "reminderStopDate",
    "sentToDebtCollection"
})
public class AFSInvoiceOutput
    extends AFSInvoice
{

    @XmlElement(name = "AccountingMonth")
    protected Integer accountingMonth;
    @XmlElement(name = "AccountingYear")
    protected Integer accountingYear;
    @XmlElement(name = "Balance")
    protected BigDecimal balance;
    @XmlElementRef(name = "BuyCancelledDate", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> buyCancelledDate;
    @XmlElementRef(name = "BuyDate", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> buyDate;
    @XmlElement(name = "BuyStop")
    protected Boolean buyStop;
    @XmlElementRef(name = "CashDiscountBalance", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<BigDecimal> cashDiscountBalance;
    @XmlElementRef(name = "CashDiscountDescription", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> cashDiscountDescription;
    @XmlElement(name = "CashDiscountUsed")
    protected Boolean cashDiscountUsed;
    @XmlElement(name = "Ins")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar ins;
    @XmlElement(name = "InterestStop")
    protected Boolean interestStop;
    @XmlElementRef(name = "InterestStopDate", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> interestStopDate;
    @XmlElement(name = "IsBought")
    protected Boolean isBought;
    @XmlElement(name = "IsInterestNote")
    protected Boolean isInterestNote;
    @XmlElementRef(name = "LastEvent", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lastEvent;
    @XmlElementRef(name = "NextEvent", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nextEvent;
    @XmlElement(name = "ProductionStop")
    protected Boolean productionStop;
    @XmlElement(name = "ReminderStop")
    protected Boolean reminderStop;
    @XmlElementRef(name = "ReminderStopDate", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> reminderStopDate;
    @XmlElement(name = "SentToDebtCollection")
    protected Boolean sentToDebtCollection;

    /**
     * Gets the value of the accountingMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountingMonth() {
        return accountingMonth;
    }

    /**
     * Sets the value of the accountingMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountingMonth(Integer value) {
        this.accountingMonth = value;
    }

    /**
     * Gets the value of the accountingYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccountingYear() {
        return accountingYear;
    }

    /**
     * Sets the value of the accountingYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccountingYear(Integer value) {
        this.accountingYear = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBalance(BigDecimal value) {
        this.balance = value;
    }

    /**
     * Gets the value of the buyCancelledDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getBuyCancelledDate() {
        return buyCancelledDate;
    }

    /**
     * Sets the value of the buyCancelledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setBuyCancelledDate(JAXBElement<XMLGregorianCalendar> value) {
        this.buyCancelledDate = value;
    }

    /**
     * Gets the value of the buyDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getBuyDate() {
        return buyDate;
    }

    /**
     * Sets the value of the buyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setBuyDate(JAXBElement<XMLGregorianCalendar> value) {
        this.buyDate = value;
    }

    /**
     * Gets the value of the buyStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBuyStop() {
        return buyStop;
    }

    /**
     * Sets the value of the buyStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBuyStop(Boolean value) {
        this.buyStop = value;
    }

    /**
     * Gets the value of the cashDiscountBalance property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public JAXBElement<BigDecimal> getCashDiscountBalance() {
        return cashDiscountBalance;
    }

    /**
     * Sets the value of the cashDiscountBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setCashDiscountBalance(JAXBElement<BigDecimal> value) {
        this.cashDiscountBalance = value;
    }

    /**
     * Gets the value of the cashDiscountDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCashDiscountDescription() {
        return cashDiscountDescription;
    }

    /**
     * Sets the value of the cashDiscountDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCashDiscountDescription(JAXBElement<String> value) {
        this.cashDiscountDescription = value;
    }

    /**
     * Gets the value of the cashDiscountUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCashDiscountUsed() {
        return cashDiscountUsed;
    }

    /**
     * Sets the value of the cashDiscountUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCashDiscountUsed(Boolean value) {
        this.cashDiscountUsed = value;
    }

    /**
     * Gets the value of the ins property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIns() {
        return ins;
    }

    /**
     * Sets the value of the ins property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIns(XMLGregorianCalendar value) {
        this.ins = value;
    }

    /**
     * Gets the value of the interestStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInterestStop() {
        return interestStop;
    }

    /**
     * Sets the value of the interestStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInterestStop(Boolean value) {
        this.interestStop = value;
    }

    /**
     * Gets the value of the interestStopDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getInterestStopDate() {
        return interestStopDate;
    }

    /**
     * Sets the value of the interestStopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setInterestStopDate(JAXBElement<XMLGregorianCalendar> value) {
        this.interestStopDate = value;
    }

    /**
     * Gets the value of the isBought property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBought() {
        return isBought;
    }

    /**
     * Sets the value of the isBought property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBought(Boolean value) {
        this.isBought = value;
    }

    /**
     * Gets the value of the isInterestNote property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInterestNote() {
        return isInterestNote;
    }

    /**
     * Sets the value of the isInterestNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInterestNote(Boolean value) {
        this.isInterestNote = value;
    }

    /**
     * Gets the value of the lastEvent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLastEvent() {
        return lastEvent;
    }

    /**
     * Sets the value of the lastEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLastEvent(JAXBElement<String> value) {
        this.lastEvent = value;
    }

    /**
     * Gets the value of the nextEvent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNextEvent() {
        return nextEvent;
    }

    /**
     * Sets the value of the nextEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNextEvent(JAXBElement<String> value) {
        this.nextEvent = value;
    }

    /**
     * Gets the value of the productionStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProductionStop() {
        return productionStop;
    }

    /**
     * Sets the value of the productionStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProductionStop(Boolean value) {
        this.productionStop = value;
    }

    /**
     * Gets the value of the reminderStop property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReminderStop() {
        return reminderStop;
    }

    /**
     * Sets the value of the reminderStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReminderStop(Boolean value) {
        this.reminderStop = value;
    }

    /**
     * Gets the value of the reminderStopDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getReminderStopDate() {
        return reminderStopDate;
    }

    /**
     * Sets the value of the reminderStopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setReminderStopDate(JAXBElement<XMLGregorianCalendar> value) {
        this.reminderStopDate = value;
    }

    /**
     * Gets the value of the sentToDebtCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSentToDebtCollection() {
        return sentToDebtCollection;
    }

    /**
     * Sets the value of the sentToDebtCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSentToDebtCollection(Boolean value) {
        this.sentToDebtCollection = value;
    }

}
