//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSLedgerResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSLedgerResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSResponseBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Ledger" type="{http://Horizon.ExternalServices.AFS}AFSLedger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSLedgerResponse", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "ledger"
})
public class AFSLedgerResponse
    extends AFSResponseBase
{

    @XmlElementRef(name = "Ledger", namespace = "http://Horizon.ExternalServices.AFS", type = JAXBElement.class, required = false)
    protected JAXBElement<AFSLedger> ledger;

    /**
     * Gets the value of the ledger property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AFSLedger }{@code >}
     *     
     */
    public JAXBElement<AFSLedger> getLedger() {
        return ledger;
    }

    /**
     * Sets the value of the ledger property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AFSLedger }{@code >}
     *     
     */
    public void setLedger(JAXBElement<AFSLedger> value) {
        this.ledger = value;
    }

}
