//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSOrderOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSOrderOptions"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://Horizon.ExternalServices.AFS}AFSOptionsBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountOfferType" type="{http://schemas.datacontract.org/2004/07/Horizon.AFS.General.Ledger.Reservation}AccountOfferType" minOccurs="0"/&gt;
 *         &lt;element name="NoInvoicePurchase" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OrderActivationType" type="{http://schemas.datacontract.org/2004/07/Horizon.AFS.General.Ledger}AFSOrderActivationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSOrderOptions", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "accountOfferType",
    "noInvoicePurchase",
    "orderActivationType"
})
public class AFSOrderOptions
    extends AFSOptionsBase
{

    @XmlElement(name = "AccountOfferType")
    @XmlSchemaType(name = "string")
    protected AccountOfferType accountOfferType;
    @XmlElement(name = "NoInvoicePurchase")
    protected Boolean noInvoicePurchase;
    @XmlElement(name = "OrderActivationType")
    @XmlSchemaType(name = "string")
    protected AFSOrderActivationType orderActivationType;

    /**
     * Gets the value of the accountOfferType property.
     * 
     * @return
     *     possible object is
     *     {@link AccountOfferType }
     *     
     */
    public AccountOfferType getAccountOfferType() {
        return accountOfferType;
    }

    /**
     * Sets the value of the accountOfferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountOfferType }
     *     
     */
    public void setAccountOfferType(AccountOfferType value) {
        this.accountOfferType = value;
    }

    /**
     * Gets the value of the noInvoicePurchase property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoInvoicePurchase() {
        return noInvoicePurchase;
    }

    /**
     * Sets the value of the noInvoicePurchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoInvoicePurchase(Boolean value) {
        this.noInvoicePurchase = value;
    }

    /**
     * Gets the value of the orderActivationType property.
     * 
     * @return
     *     possible object is
     *     {@link AFSOrderActivationType }
     *     
     */
    public AFSOrderActivationType getOrderActivationType() {
        return orderActivationType;
    }

    /**
     * Sets the value of the orderActivationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AFSOrderActivationType }
     *     
     */
    public void setOrderActivationType(AFSOrderActivationType value) {
        this.orderActivationType = value;
    }

}
