//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AFSObjectBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AFSObjectBase"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AFSObjectBase", namespace = "http://Horizon.ExternalServices.AFS")
@XmlSeeAlso({
    AFSOrderShipment.class,
    AFSReport.class,
    AFSOrderShipmentInvoiceInfo.class,
    AFSAccountTermsAndConditionsRequest.class,
    AFSAccountTermsAndConditionsSecciRequest.class,
    AFSAcceptAccountTermsAndConditionsRequest.class,
    AFSAccountCheckCustomerHasAccountRequest.class,
    AFSReservationWithPaymentType.class,
    AFSCancelReservation.class,
    AFSAdditionalReservationInfo.class,
    AFSInvoiceTextRequest.class,
    AFSUpdateInvoiceDueDateRequest.class,
    AFSUpdateInvoiceStopFlagsRequest.class,
    AFSUpdateMerchantInfoRequest.class,
    AFSGetDirectDebitContractRequest.class,
    AFSAcceptDirectDebitContractRequest.class,
    AFSGetClientLimitRequest.class,
    AFSGetVirtualBankAccountRequest.class,
    AFSUpdateCustomerEinvoiceInfoRequest.class,
    AFSCustomer.class,
    AFSOptionsBase.class,
    AFSPurchaseStatus.class,
    AFSPurchaseDeclineReason.class,
    AFSLedger.class,
    AFSVoucher.class,
    AFSInvoice.class,
    AFSInvoiceAccountInfo.class,
    AFSInvoiceLine.class,
    AFSCustomerCheckStatus.class,
    AFSCustomerCheckDeclineReason.class,
    AFSOrder.class,
    AFSOrderLine.class,
    AFSOrderSearch.class,
    AFSOrderShipmentDetail.class,
    AFSReportDocument.class,
    AFSReportParameter.class,
    AFSReportLink.class,
    AFSReservation.class,
    AFSInvoiceTextOutput.class
})
public class AFSObjectBase {


}
