//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 07:46:24 PM CET 
//


package com.company.project.stubs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfAFSOrderSearch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfAFSOrderSearch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AFSOrderSearch" type="{http://Horizon.ExternalServices.AFS}AFSOrderSearch" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfAFSOrderSearch", namespace = "http://Horizon.ExternalServices.AFS", propOrder = {
    "afsOrderSearch"
})
public class ArrayOfAFSOrderSearch {

    @XmlElement(name = "AFSOrderSearch", nillable = true)
    protected List<AFSOrderSearch> afsOrderSearch;

    /**
     * Gets the value of the afsOrderSearch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the afsOrderSearch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAFSOrderSearch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AFSOrderSearch }
     * 
     * 
     */
    public List<AFSOrderSearch> getAFSOrderSearch() {
        if (afsOrderSearch == null) {
            afsOrderSearch = new ArrayList<AFSOrderSearch>();
        }
        return this.afsOrderSearch;
    }

}
